export const UPDATE_TOURNAMENT = "UPDATE_NEW_TOURNAMENT";
export const UPDATE_TOURNAMENTS = "UPDATE_TOURNAMENTS";
export const UPDATE_ACCOUNT = "UPDATE_NEW_ACCOUNT";
export const UPDATE_IDS = "UPDATE_IDS";
