export const initialState = {
  tournament: {
    title: "",
    date: "2000-01-10",
    time: "00:00",
    venue: "",
    address: "",
    city: "",
    state: "",
    zipcode: "",
    inOrOut: "",
    courts: 0,
    gender: "",
    minAge: 0,
    skill: [0, 0],
    type: "",
    fee: 0,
    open: "2000-01-10",
    deadline: "2000-01-10",
    contact: "",
    phone: "",
    organizer: "",
    details: "",
    participants: [],
    maxPlayers: 0,
  },
  tournaments: [],
  account: {
    name: "",
    phone: "+1",
    zipcode: "",
    birthdate: "1900-01-10",
    skill: 0,
    gender: "",
    userEmail: "",
    tournaments: [],
  },
};
