export const initialState = {
  tournament: {
    title: "",
    date: "2020-05-20",
    time: "00:00",
    venue: "",
    address: "",
    city: "",
    state: "",
    zipcode: "",
    inOrOut: "",
    courts: 1,
    gender: "Mixed",
    minAge: 0,
    skill: [0, 6],
    type: "Modified",
    fee: 0,
    open: "2020-05-20",
    deadline: "2020-05-20",
    contact: "",
    phone: "+1",
    organizer: "",
    details: "",
    participants: [],
    maxPlayers: 16,
  },
  tournaments: [],
  account: {
    name: "",
    phone: "+1",
    zipcode: "",
    birthdate: "2020-05-20",
    skill: 0,
    gender: "",
    userEmail: "",
  },
  ids: [],
};
